{
    'game': 'CartPole-v1',
    'gamma': 0.99,
    'batch_size': 128,
    'eps_start': 0.9,
    'eps_end': 0.05,
    'eps_decay': 1000,
    'save_every': 2,

    'lr_start': '1e-4',
    'lr_end': '1e-6',
    'lr_decay': 2000,
    'epoch': 200,
    'pretrain_data_path': 'data\data_save\data.csv',
    'pretrain_model_path': 'data\model\pretrain_model.pth',
    'final_model_path': 'data\model\final_model.pth',
    'save_model_path': 'data\model\save_model.pth'
}