{
    'game': 'CartPole-v1',
    'lr_start': 0.00001,
    'lr_end': 0.0000001,
    'lr_decay': 2000,
    'batch_size': 128,
    'epoch': 200,
    'pretrain_data_path': 'D:\workspace\data\hello_rl_data\data.csv',
    'pretrain_model_path': 'D:\workspace\data\hello_rl_data\pretrain_model.pth',
    'final_model_path': 'D:\workspace\data\hello_rl_data\final_model.pth',
    'save_model_path': 'D:\workspace\data\hello_rl_data\save_model.pth'
}